/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 785154d4d67f435a99b5365aece0ea2c.glb 
Author: みそ太郎 (https://sketchfab.com/nama_140)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mbf-02-strike-rouge-ootori-785154d4d67f435a99b5365aece0ea2c
Title: ストライクルージュ(オオトリ装備)/MBF-02 Strike Rouge Ootori
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/785154d4d67f435a99b5365aece0ea2c.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="9a3a2feccd594c7bac4b4c96bde0da87fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="������������������_arm" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_56" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_59" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials['00-ROUGE']} skeleton={nodes.Object_57.skeleton} />
                    <skinnedMesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.OOTORI} skeleton={nodes.Object_58.skeleton} />
                    <skinnedMesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.BEAM} skeleton={nodes.Object_60.skeleton} />
                  </group>
                </group>
                <group name="������������������" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="���������������������" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/785154d4d67f435a99b5365aece0ea2c.glb')
